// Code generated by "stringer -type=TypeBrickOp"; DO NOT EDIT.

package opinterface

import "fmt"

// var _Call_map []string = {"OpNil", "OpCallbb", "OpCalldd"}

func (ind TypeCallOp) String() string {
	_Call_map := []string{"OpNil", "OpCallbb", "OpCalldd"}
	if ind >= OpMaxCall {
		return fmt.Sprintf("TypeCallOp(%d)", ind)
	}
	return _Call_map[uint32(ind)-OpCallbb+1]
}
